### ISSUE TITLE
Error on getting categories

### ISSUE THREAD

**Issue by aptonline** [pemre/iptv-cli#3]
Hi, brand new install and attempting to parse a local m3u file is giving me the following error when getting categories:

```
/usr/local/lib/node_modules/iptv-cli/node_modules/m3u8-file-parser/src/parser/extinf.js:55
        token = str.slice(pos + 1, match.index);
                                         ^

TypeError: Cannot read property 'index' of null
    at Object.extinf [as parser] (/usr/local/lib/node_modules/iptv-cli/node_modules/m3u8-file-parser/src/parser/extinf.js:55:42)
    at M3U8FileParser.invokeParser (/usr/local/lib/node_modules/iptv-cli/node_modules/m3u8-file-parser/src/reader.js:77:46)
    at M3U8FileParser.read (/usr/local/lib/node_modules/iptv-cli/node_modules/m3u8-file-parser/src/reader.js:59:12)
    at getChannelsFromFile (/usr/local/lib/node_modules/iptv-cli/src/lib/helpers.js:14:10)
    at getCategories (/usr/local/lib/node_modules/iptv-cli/src/commands/get-categories.js:7:16)
    at Proxy.cli (/usr/local/lib/node_modules/iptv-cli/src/cli.js:31:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/iptv-cli/index.js:3:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

An idea what's going wrong?  Thanks.

**Comment by pemre** [comment]
#2 (which fixes #1) should've fixed your problem, let me know if it didn't. I just published v0.2.1 on npm.
